# Generated by Django 3.1.7 on 2021-03-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceAttend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='f_password',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
