# Generated by Django 3.1.7 on 2021-03-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceAttend', '0002_auto_20210309_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='f_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_password',
            new_name='password',
        ),
    ]
